update-readme
RoadieHQ/backstage-roadie-plugins pull request #24
Opened 2021-06-17 14:50 UTC by Irma12

2021-06-17 19:09 UTC, dtuite requested changes

2021-06-17 19:09 UTC, dtuite commented on plugins/backstage-plugin-github-pull-requests/README.md
> +If you have previously used this plugin you will be noticing some changes. In order to increase usability of our plugins and make testing and integration process straightforward and easy we are curre
My suggested version basically says the same thing, just in a shorter fashion. It's also important to tell the users what is not changing, to proactively answer the top questions that may pop up in their minds.

```suggestion
In order to make testing and deployment of our plugins easier we are migrating all Roadie plugins to a monorepo at https://github.com/RoadieHQ/backstage-roadie-plugins.

The plugins will still be published to the same place on NPM and will have the same package names so nothing should change for consumers of these plugins.
```

2021-06-17 19:09 UTC, dtuite commented on plugins/backstage-plugin-github-pull-requests/README.md
> +We have decided to gather all of our plugins repositories in one place, so it is easier to find everything you need, which will boost the usage and hopefully give better overview of everything you ca
```suggestion
```

2021-06-17 19:09 UTC, dtuite commented on plugins/backstage-plugin-github-pull-requests/README.md
> +From now on, this plugin will be contained inside https://github.com/RoadieHQ/backstage-roadie-plugins repository, which will gather all of the plugins we, at Roadie, have worked on.
```suggestion
```

2021-06-17 19:09 UTC, dtuite commented on plugins/backstage-plugin-github-pull-requests/README.md
> +Updated instructions could be found below:
```suggestion
```

2021-06-17 19:09 UTC, dtuite commented on plugins/backstage-plugin-github-pull-requests/README.md
> +## Notice
```suggestion
## Repository migration notice
```

I want to make this heading a little more alarming so people read it.

2021-06-18 08:33 UTC, martina-if commented
related to #6

2021-06-18 08:35 UTC, dtuite approved these changes

2021-06-18 08:36 UTC, merged